DOCUMENTS_PREFIX = "documents"
PRESIGNED_PUT_EXPIRES = 900   # 15 分
PRESIGNED_GET_EXPIRES = 300   # 5 分
MAX_FILE_SIZE_BYTES = 100 * 1024 * 1024  # 100 MB
DEFAULT_PAGE_LIMIT = 20
MAX_PAGE_LIMIT = 100

# DynamoDB キープレフィックス
PK_DOC = "DOC#"
SK_META = "META"
SK_VER_PREFIX = "VER#"
PK_TAG = "TAG#"
PK_AUDIT = "AUDIT#"

# GSI 名
GSI1 = "gsi1"
GSI2 = "gsi2"
